
= Cloudclapp(TM) (CCLA) Documentation
ifndef::imagesdir[:imagesdir: images]
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

== Quick access ==

[cols="1*"] 
|===

a| link:user-guide/user-guide-single{outfilesuffix}[User Guide,window=_blank]link:ccla/pdf/user-guide/user-guide-single.pdf[(pdf),window=_blank] 

a| link:user-guide/quickstart{outfilesuffix}[Quickstart,window=_blank]

|===

== Release Notes ==

[cols="1*"] 
|===

a| link:release-notes/release_notes{outfilesuffix}[Release Notes,window=_blank]link:ccla/pdf/release-notes/release_notes.pdf[(pdf),window=_blank]

a| link:release-notes/release_ccla_1.1.0{outfilesuffix}[CCLA 1.1.0,window=_blank]

a| link:release-notes/release_ccla_1.0.0{outfilesuffix}[CCLA 1.0.0,window=_blank]

a| link:release-notes/release_ccla_mvp4{outfilesuffix}[CCLA MVP4,window=_blank]

a| link:release-notes/release_ccla_mvp3{outfilesuffix}[CCLA MVP3,window=_blank]

a| link:release-notes/release_ccla_mvp2{outfilesuffix}[CCLA MVP2,window=_blank]

a| link:release-notes/release_ccla_mvp1{outfilesuffix}[CCLA MVP1,window=_blank]

|===
