= REST API
:doctype: book
:imagesdir: ./resources/
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:toc: left
:toclevels: 4 
:source-highlighter: pygments

The {product_name} provides a support for REST API. These API can be used by third-party service, application or script to manage your {product_name} instance.

== Enabling REST API support
The API is enabled by default. No additional configuration is required.

[#authentication]
== Authentication
When making requests to {product_name} using the REST API, you will need:

* A valid admin username and password (so that a token can be generated and an authenticated session can be established).
* Appropriate access permissions for the requested resource (controlled by admin profile)

Using curl, you may save the authentication information as a HTTP header to allow subsequent requests to be accepted automatically.

----
curl -H 'Content-Type: application/json' -XPOST http://<MSA IP or FQDN>/ubi-api-rest/auth/token -d '{"username":"username", "password":"user password"}'
----

----
curl -H 'Accept: application/json' -H "Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJuY3Jvb3QiLCJpYXQiOjE1NTY1MzUzMzUsImx2bCI6IjEiLCJleHAiOjE1NTY2MjE3MzV9.bQUkXYK7wISMyQ4zbrU0vGc2EO0cwlZKfkef85JxYH8eHiDKyOgiSBVF-IuVzFuoiErr9LzGM9gxZ1nbqyumuA" -XGET 'http://<MSA IP or FQDN>/ubi-api-rest/user/customer-by-manager-id/1
----

== Format
{product_name} API uses the JSON format.


== Example API commands
For the full list of available commands, see the {product_name} API guide on your {product_name} instance: http://<MSA IP or FQDN>/swagger

=== User login
*HTTP Request:* `+/ubi-api-rest/auth/token+`

*Method:* `+POST+`
[cols=3*,options="header"]
|===
| Parameter Name
| Type
| Description

| username
| String
| User name

| password
| String
| Password
|===

*Example:*
[source,json]
----
{
	"username": "test",
	"password": "test1234567890"
}
----
*Response:*
[source,json]
----
{
	"token": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNTgyMjk5NDkxLCJsdmwiOiIzIiwiZXhwIjoxNTgyMzg1ODkxfQ.FAtw4MRrAd92X7IbSBJA0Ik9hSCO-XR1DCgmTIS2U8dTmndCP1dTx72WkD5cDQJ8L3VCvbIWGwZRlUalfsak-g",		// <1>
	"message": "authenticated",
	"authenticated": "true",
	"userDetails": {
		"id": 18,
		
		... // <2>
		
		"externalReference": "UBIG18",
		"login": "test",
		"firstname": "",
		"manageAllUsers": true,
		"name": "test",
		"sort": "NAME",
		"ldapAuthentication": false,
		"delegationProfilePerCustomer": {}
	}
}
----
<1> the authentication token to use in the HTTP header of the REST API calls
<2> the JSON response has been shortened for this documentation

=== Ping an IP address from the CoreEngine

*HTTP Request:* `+/ubi-api-rest/device/ping/{$ip_address}+`

*Method:* `+GET+`
[cols=3*,options="header"]
|===
| Parameter Name
| Type
| Description

| ip_address
| String
| The IP address to ping

|===

*Example:*
[source]
----
/ubi-api-rest/device/ping/127.0.0.1
----
*Response:*
[source,json]
----
{
	"status": "OK",
	"rawJSONResult": "{\"sms_status\":\"OK\",\"sms_code\":\"\",\"sms_message\":\"--- 127.0.0.1 ping statistics ---\\n5 packets transmitted, 5 received, 0% packet loss, time 3999ms\\nrtt min/avg/max/mdev = 0.031/0.036/0.043/0.006 ms\"}",
	"message": "--- 127.0.0.1 ping statistics ---\n5 packets transmitted, 5 received, 0% packet loss, time 3999ms\nrtt min/avg/max/mdev = 0.031/0.036/0.043/0.006 ms"
}
----

=== Call IMPORT from a microservice 
*HTTP Request:* `+/ubi-api-rest/ordercommand/execute/{device_id}/{command_name}+`

*Method:* `+POST+`
[cols=3*,options="header"]
|===
| Parameter Name
| Type
| Description

| device_id
| Long
| The database identifier of the Managed Entity

|command_name
|String
|One of CREATE, UPDATE, DELETE

|body
|String
|the payload with the microservice parameters

|===
*Example:*
[source]
----
/ubi-api-rest/ordercommand/execute/156/CREATE
----
[source,json]
----
{
	"simple_firewall": {
		"789": {
			"object_id": "789",
			"src_ip": "7.8.3.0",
			"src_mask": "255.255.255.0",
			"dst_ip": "8.8.3.0",
			"dst_mask": "255.255.255.0",
			"service": "http",
			"action": "deny"
		}
	}
}
----
*Response:*
[source,json]
----
{
	"commandId": 0,
	"status": "OK",
	"message": "access-list 789 extended deny object http 7.8.3.0 255.255.255.0 8.8.3.0 255.255.255.0 log\n"
}
----

[#conf_variables]
=== Configuration variables

*HTTP Request:* `+/variables/{deviceId}/{name}+`

*Method:* `+GET+`
[cols=3*,options="header"]
|===
| Parameter Name
| Type
| Description

| deviceId
| Long
| Id of device (Number format) has to be higher than 0, Example = 3453

| name
| String
| Name of the variable, Example = var1

|===


[#msa_configuration]
=== {product_name} configuration

*HTTP Request:* `+/system-admin/v1/msa_vars+`

*Method:* `+POST+`

*Body:*
[source, json]
----
[
  {
    "name": "string",
    "lastUpdate": "string",
    "comment": "string",
    "value": "string"
  }
]
----


