=== Fresh install or upgrade ?

The quickstart repository is maintained on https://github.com/ubiqube/quickstart and the latest version is available on the branch master.

If you are upgrading your {product_name}, you can either do a clean install for the quickstart by removing your docker containers and the quickstart directory and go to step 2. above or you can update your quickstart with `cd quickstart` and do `git pull` to get the latest version.

NOTE: In case you have updated the {product_name} with `docker-compose up -d` or `docker-compose pull`, you might experience cache issues (for instance, your changes may not be reflected on the UI). To solve that, you can clean your browser cache, or use a browser private session.


=== Install a specific version

For each release of the {product_name}, there is a tag that you can use if you need to install a specific version of the product.

To install a tagged version, you can checkout the tag and go to the install steps above.

For example, the CLI command below will checkout the quickstart for the release {revnumber}.
----
git checkout tags/{revnumber} -b {revnumber}
----

The releases and tags are available link:https://github.com/ubiqube/quickstart/releases[here]
