= Troubleshooting guide
:toc: left
:toclevels: 4 
:doctype: book :imagesdir: ./resources/
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:source-highlighter: pygments

== Containers / Docker Engine
=== How do I check that the Docker containers are deployed ?
On a Linux system from the directory where you ran the `docker-compose up -d` command (working directory), run `docker-compose images`.

[source]
----
$ docker-compose images
   Container                Repository                Tag         Image Id       Size  
---------------------------------------------------------------------------------------
docker_api_1       ubiqube/msa2                   api-20.0      59703619e8f0   7.111 GB
docker_camunda_1   camunda/camunda-bpm-platform   7.12.0        ccda669a96fc   255.1 MB
docker_db_1        ubiqube/msa2                   db-20.0       e8eee0194267   5.537 GB
docker_es_1        ubiqube/msa2                   es-20.0       e3844db59c35   5.537 GB
docker_front_1     ubiqube/msa2                   front-20.0    3f96ebe79bc5   10.71 MB
docker_kibana_1    ubiqube/msa2                   kibana-20.0   8e8f14f8b2c9   5.537 GB
docker_ui_1        ubiqube/msa2                   ui-20.0       517fea2710fa   34.71 MB
----
- *front*: runs the UI
- *api*: runs the CoreEngine, the API server and the legacy UI
- *db*: runs the PostgreSQL database
- *camunda*: runs the BPM
- *es*: runs the Elasticsearch server
- *kibana*: run the Kibana server

Verify that all the containers are up.

This will also show you the network port mapping.

[source]
----
$ docker-compose ps
      Name                  Command             State                               Ports                             
----------------------------------------------------------------------------------------------------------------------
docker_api_1       /sbin/init                   Up      0.0.0.0:2223->22/tcp                                          
docker_camunda_1   /sbin/tini -- ./camunda.sh   Up      8000/tcp, 8080/tcp, 9404/tcp                                  
docker_db_1        run ubi-base                 Up                                                                    
docker_es_1        run elasticsearch            Up                                                                    
docker_front_1     nginx -g daemon off;         Up      0.0.0.0:443->443/tcp, 0.0.0.0:514->514/udp, 0.0.0.0:80->80/tcp
docker_kibana_1    run kibana                   Up                                                                    
docker_ui_1        nginx -g daemon off;         Up      80/tcp      
----

== User Interface
=== I can't login to the user interface (UI)

Here are a set of useful CLI commands that you can run from the working directory ...

Check the status of the main service in the container "api":
[source]
----
$ docker-compose exec api /opt/sms/bin/check_services_status.sh
wildfly                                                    [  OK  ]
tomcat                                                     [  OK  ]
ubi-dms                                                    [  OK  ]
ubi-sms                                                    [  OK  ]
ubi-webconf                                                [  OK  ]
----

Check the status of the database:
[source]
----
$ docker-compose exec db service postgresql-9.3 status
postgresql-9.3 (pid  52) is running...
----

Monitor the logs of the API server. Run the cmd below and try to login.
Report any error from the logs:
[source]
----
docker-compose exec api tail -F /opt/wildfly/logs/console.log
----

If the API server is not responding or if you can't login after a few minutes, run the command below to restart the API server and monitor the logs:
[source]
----
$ docker-compose exec api service wildfly restart              
removing previous configuration
setting new configuration
error reading input file

[...]

BUILD SUCCESSFUL
Total time: 0 seconds
moving ear to /opt/wildfly/standalone/deployments/
Using Mode: standalone/
wildfly started with errors, please see server log for details            [  OK  ]
----

Then monitor the logs as explained above.

=== Wildfly startup failure `fatal KILL command`

If wildfly fails to start with an error similar to `fatal KILL command` then you probably haven't allocated enough memory to your docker engine (see link:../user-guide/quickstart{outfilesuffix}#prerequisites[prerequisites])


The above steps should resolve common reasons why the {product_name} is not functioning properly.  If there is something that is still not working properly, then please contact UBiqube.


== Configuration Engine
=== How do I enable debug logs on the SecEngine ?
The SecEngine logs are available on the API container (see link:architecture_overview{outfilesuffix}[architecture overview]) in the directory `/opt/sms/logs`.

If you are designing a Microservice or simply operating the {product_name}, you might need to monitor the logs of the configuration engine.

Run the CLI command below to tail the logs
[source]
----
$ docker-compose exec api tail -F /opt/sms/logs/smsd.log
----  

By default, DEBUG logs are not enabled.

To enable the DEBUG mode, you need to connect to the container 'api' and execute the CLI command `tstsms SETLOGLEVEL 255 255`
[source]
----
$ docker-compose exec api bash
[root@msa /]# tstsms SETLOGLEVEL 255 255
OK
[root@msa /]# 
----

This will activate the DEBUG mode until the service is restarted.

Execute `tstsms SETLOGLEVEL 0` to revert to the default log level.

