= Portal Overview
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesdir: ../resources/
:ext-relative: adoc

== Overview

The MSActivator web portal gives you centralized control over all your
managed entities, whether they are CPE or core network devices, security
devices, or even public or private cloud infrastructure managers.

== Homepage Overview

The video below will give you a quick overview of the MSActivator
homepage.

To get to the homepage you need to login using the details that were
given to you by your admin.

=== Video Tutorial

video::videos/MSActivator-16.2-Homepage-Overview.mp4[image,width=500,height=380]

== Administration Page

As a privileged administrator, you can access the administration page by
clicking on the gear icon in the top right-hand corner.

The administration window is divided into tabs as listed below:

=== Information About Your Current License

Licenses are limited to a number of devices and have an expiration date.

When you purchase a new license from UBiqube, you will receive a license
file that has to be uploaded here to activate the device functionality.

After license expiration, with a production license, your MSA will
continue to function but the product upgrade for maintenance and patch
is locked and you need to contact your UBiqube reseller to renew your
support and maintenance license.

=== (D-)MSA Status

This is mainly for distributed MSActivator setups only. In the case
where your company runs the MSActivator on multiple servers, you can see
a list of all the nodes and their statuses on this page.

=== Elasticsearch cluster

The third section provides a simplified management view of the
Elasticsearch cluster.

It gives you the ability to do simple operations on the index, for
example listing the indexes or deleting them.

NOTE: Deleting an index in a non-recoverable operation, be careful when
using it!

=== Bulk Import

This is a useful tool for companies that already have a set of existing
devices and would like to address a brownfield deployment use-case with
existing devices.

You can import lists of these existing devices or customers by uploading
a CSV file. The MSActivator will then automatically create tenants and
devices accordingly. Managers and Administrators can use this function
also.

=== Tech Report******

Use this function to generate a detailed technical report that can be
sent to UBiqube’s customer support for offline troubleshooting.

To export this, you can select “Direct Link” and copy the link from the
new window, or save the report as an HTML file on your local disk using
your browser.

==== Video Tutorial

video::videos/MSActivator-16.2-Administration-Page.mp4[image,width=500,height=380]

== Selfcare Portal

From the MSActivator portal, users can access a set of predefined
functionalities and services.

As the administrator, you control access to the selfcare portal. You
must also provide information to your users so that they can access the
selfcare portal.

=== Video Tutorial

video::videos/MSActivator-16.2-Creating-a-Self-Care-Account.mp4[image,width=500,height=380]
