= Profiles
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesdir: ../resources/
:ext-relative: adoc

Within the MSActivator, there are two kinds of profiles:

* link:../Assurance/monitoring-profile{outfilesuffix}[Monitoring Profiles]
* link:../Configuration/configuration-profile{outfilesuffix}[Configuration
Profiles] - to aggregate multiple functions for several devices.

Monitoring profiles let you define a set of Key Performance Indicators,
or KPIs, and monitor them on multiple devices.

When choosing the KPIs you want to observe, you can also add other
variables such as the frequency the information is retreived, and the
threshold for alarm generation.

This works on all kinds of devices that support SNMP, the Simple Network
Management Protocol.

Configuration profiles, on the other hand, are an easy way to configure
a set of functionalities on multiple devices.

For example, if your customer has several devices of the same kind, a
configuration profile can be created according to the service you want
to provide on all of these devices.

This process not only saves a lot of time and minimizes the risk of
manual errors - when compared to configuring each functionality for each
seperate device - but also provides a way to implement a consistent set
of managed services across multiple devices and end customers.

The profile can then be attached to the selected devices to achieve a
quick and consistent configuration. Please note that a device can only
be linked to one configuration profile.

== Video Tutorial

video::videos/MSActivator-16.2-Profiles.mp4[image,width=500,height=380]
