= Key Concepts

== Application Deployer ==

An application simply refers to any software application that will be deployed in a cloud environment.
Supported format in the current version are :

* Native container applications (from public or private dockerHub)
* VM based application/system from AWS EC2 markeplace

== Environment Builder ==

Using from a blueprint or from scratch, the environment builder permits to design your cloud architectures
In the environment home page, you can access the environment builder by clicking on Design tab

The generic library of component permit to address lots of use cases without having experties in each cloud technology

* Provider  : select on which cloud provider the design will be applied (AWS,AZURE and GOOGLE)
* Region : select on which region resources will be created. Per providers, the list is fetched
* App deployment : select 1 or multiple application to be deployed on this design (See Application Deployer)
* K8 cluster : abstract all Kubernetes services provided by public provider and private one

== Blueprints

Blueprints enable users to design infrastructure, platforms, and application services by composing and connecting cloud resources. It can be seen as a package or a  template permitting to deploy quickly an environment with predefined applications. It permits also to replicate any infrastructure to multiple platforms.

=== Catalog View ===

One of the ways to start quickly on CloudClapp is to chose from the templates'catalog the blueprint you want. When you access the blueprints view, each tile represents one blueprint. There is 2 types of blueprints :

* Blueprints from the OpenMSA library : https://github.com/openmsa/Blueprints, visible in all organizations
* Blueprints created by users of the platform, visible only in the organization where they have been created

Example of blueprints :

* Wordpress on Azure
* Load balancer on AWS
* MSActivator on any providers

=== Content ===

A Blueprint is a combinaison of two main files 

* A meta data containing basic information like name, description, owner, compliance standards, etc...
* A design file to define ressources used for the deployment and place components on the environement builder. The design file, by the nature of the component (Provider, Region, Cluster), include MSA workflows reference permit the environement creation and the deployment of applications





