= Taxonomy to drive xOPS journey

Cloudclapp has been designed to manage lifecycle of environments and cloud platforms. 
Any OPS personel can manage IT systems, be sure it remains efficient, safe and scale in continuous way. The solution allows to manage frequent changes as environments are not static, moving in the time.
3 enablements domains have been created:

== BUILD ==
Mainly via the blueprint catalog, the journey start by designing new infrastructure with easy to use designer: drag & drop generic components to build your environment and deploy your applications.
No code design, no need cloud expertise to deploy simple thing.  Combining  clouds technologies, connectivity options. Abstract concepts.

== OPERATE ==
Manage lifecycle of your environments, including discovery. Trought operate, a user can do application deployment, cost management, trigger security scanners same as accessing config management of clusters.
The solution allows also to access service mesh, observability, tracking, governance...

== AUTOMATE ==
Use or build specific processes to add extra values and manage frequent changes. It can be manual, schedule or event based. Automation blocks are sorted by categories.
Continuously improve the degree of automation of environments. 

= Key Concepts

== An organization

An organization represents a group of people (admin or users) sharing same environments.

An organization is created through the *Get started* form in the cloudclapp login page.

The same instance of Cloudclapp can host multiple organizations

_Note: An admin can belong to multiple organizations. This operation is done using MSactivator portal_

== An Application

An application simply refers to any software application that will be deployed in a cloud environment.
Supported format in the current version are:

* *Native container applications* (from public or private dockerHub)
* *VM based application/system* from AWS EC2 markeplace

=== Marketplace

Marketplace designed the place where applications are coming from. Currently, we support:

* *Public Docker Hub*: https://hub.docker.com/
* *Private Docker Hub*
* *EC2 AWS Martketplace*: https://aws.amazon.com/marketplace

=== A deployment

A deployment represents one or multiple applications deployed in an environment.

Example of deployment:

* Wordpress + Mysql as container images (deployed on K8 cluster)
* A MongoDB as a container image (deployed on K8 cluster)
* Windows server instance (deployed on AWS EC2)

Refers to link:application_deployer.adoc[Application Deployer,window=_blank] for more details.

== An Environment

An environment represents an infrastructure developed to provide applications. An environment is represented by a tile in organization dashboard or environement view. It could be:

* A *K8 cluster* in Amazon (EKS), Azure (AKS), Google (GKE) or nativaley imported
* A *virtual server* in Amazon (EC2)
* A *combination of cloud services* (multi or hybrid cloud)

=== Environment Builder ===

Using from a blueprint, the environment builder permits to design your cloud architectures. In the environment home page, you can access the environment builder by clicking on Design tab

The generic library of component permit to address lots of use cases without having experties in each cloud technology

* *Provider:* select on which cloud provider the design will be applied (AWS, AZURE and GOOGLE)
* *Region*: select on which region resources will be created. Per providers, the list is fetched
* *App deployment*: select 1 or multiple application to be deployed on this design (See Application Deployer)
* *K8 cluster*: abstract all Kubernetes services provided by public provider and private one
* *Mesh*: permit to interconnect application between remote clouds

For more details refers to link:environment_builder.adoc[Environment Builder,window=_blank]

== Blueprint

Blueprints enable users to design infrastructure, platforms, and application services by composing and connecting cloud resources. It can be seen as a package or a  template permitting to deploy quickly an environment with predefined applications. It permits also to replicate any infrastructure to multiple platforms.

=== Catalog View

One of the ways to start quickly on CloudClapp is to choose from the templates'catalog the Blueprint you want. When you access the Blueprints view, each tile represents one Blueprint. There is 2 types of Blueprints:

* Blueprints from the OpenMSA library: https://github.com/openmsa/Blueprints, visible in all organizations
* Blueprints created by users of the platform, visible only in the organization where they have been created

Example of Blueprints:

* *Wordpress on Azure*
* *Wordpress on multicloud*
* *MSactivator on any providers*

=== Content

A Blueprint is a combinaison of two main files: 

* *A meta data* containing basic information like name, description, owner, compliance standards, etc...
* *A design file* to define resources used for the deployment and place components on the environement builder. The design file, by the nature of the component (Provider, Region, Cluster), include MSactivator workflows reference permit the environement creation and the deployment of applications

== Users

=== A manager
An admin is the creator of one organization. He has full access to all features inside an organization. He has no restriction to deploy infrastructures on any cloud providers.

_Note: it's possible to add multiple admins in the same organization using MSactivator_

=== A user

A user is simple person who can access the same admin's organization. By default, he is limited to read-only actions when he joins the first time the organization

Via permissions screen, an admin can assign some rights to extend actions like create environment, deploy application, access insight screen.

