= Device Status
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesdir: ../resources/
:ext-relative: adoc

== Overview

Every device that is configured with the MSActivator has a status. The
status of each device is shown in the device list as a coloured dot next
to the device’s name.

Device statuses are generated by evaluating the connectivity between the
MSActivator and each device. By default, the MSActivator uses the
Internet Control Message Protocol, or ICMP, to check connectivity.

There are four different statuses. Blue means that this device has never
been activated before and requires
link:../Getting_Started/managed-devices{outfilesuffix}[initial provisioning].

Red means that the device has been activated before, but it is not
reachable at the moment.

A yellow dot indicates a critical status. The status is critical if the
device cannot be reached for a duration of 5 minutes. After these 5
minutes have passed, and if the device is still unreachable, its status
is set to red. If the device can be reached within these 5 minutes,
however, its status is set back to green.

A green dot means that the connectivity between the MSActivator and the
device has been established and it is working properly.

Administrators can see an overview of device statuses of each tenant and
customer in the “Customers” Tab.

=== Video Tutorial

video::videos/MSActivator-16.2-Device-Status.mp4[image,width=500,height=380]
