= Managed Entities
:doctype: book
:imagesdir: ./resources/
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

In order to become a manageable entity in the {product_name}, an entity has to be created and activated in the {product_name}.

== Create, Update and Activate a Managed Entity
To create a Managed Entity, click the "Create" button on the Managed Entity Listing page.
 
This will bring you to the Create Managed Entity form.

The fields marked with a "*" are required to create a Managed Entity. 
If a tenant or customer is selected on the global filter, then they will be pre-populated in the form. Otherwise a tenant and customer must be selected.

The selections in the "Vendor" and "Model" fields will determine the fields displayed in the "Management Information" and "Advanced Information" sections. 
Different Managed Entity types have different associated variables that are used in their provisioning and operation.

NOTE: the selection of the vendor and model will determine the Adapter that will be used by the CoreEngine for configuration and assurance. 
It's important to select an adapter that is compatible with the managed entity model.
Once a managed entity is created, it is not possible to change the model, the managed entity will have to be recreated.

The Create Managed Entity form can be closed by pressing the "X" button in the top bar. Any data entered into the fields will be preserved for when the user returns to the form. Clicking the "Discard Changes" button will display a prompt confirming that all changes will be lost. 
If the user accepts the form state will be reset.

The update form can be accessed by clicking the pencil icon on the Managed Entity Listing page or on the Managed Entity Detail page.

=== Managed Entity Activation
A Managed Entity can be activated by pressing the "Activate" button the Managed Entity Detail screen.

This will show a form that takes the variables such as management IP, username and password that will be used in the activation. 
These fields may be pre-populated by the values given in the create form. 
If the variables are updated they will be used for that particular activation but will not be persistent.

When the activation is started the dialog shows the progress of the Managed Entity activation. 
This will update as the activation progresses and will show whether the activation succeeds or fails.

NOTE: the activation of the managed entity is excuted by the Adapter specific to the Managed Entity model.
//// 
TODO : add detail screen info when screen is not static anymore



== Managed Entity Detail Screen
The managed entity details screen is used to display the details of the selected entity.  
You can reach this screen via searching for a managed entity via the global search feature in the top navigation, or by selected an entity in the managed entities list:
The information such as the serial number, firmware, memory ... are retreived dynamically by the entity adapter once the entity is activated.

include::./managed_entity_lifecycle{outfilesuffix}[]

include::./managed_entity_history{outfilesuffix}[]

////
