= クイックスタートガイド 
:doctype: book
:imagesdir: ./resources/
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

////
TODO update for 2.2
////

== インストール手順

.step 1
UBiqube社員に、MSA2トライアル希望の旨を連絡願います。後述するイメージへのリポジトリへのlink:https://docs.docker.com/docker-hub/access-tokens/[access token]を払い出します。

.step 2
docker/docker-composeをマシンにインストールしてください。

.step 3
任意のディレクトリ上で、以下のコマンドを実行してください。

1. `$ git clone https://github.com/ubiqube/quickstart.git` 
2. `$ cd quickstart`
3. `git checkout tags/{revnumber} -b {revnumber}`
4. `$ sudo docker login` 
5. `$ sudo docker-compose up -d` 

IMPORTANT: `docker login`にてユーザ情報を聞かれますので、ID"msa2trial"と、1で払い出したアクセストークンを使用して下さい。

.step 5
ブラウザからhttps://localhost/ にアクセスしてください。

.step 6
user:ncroot, password:ubiqubeで{product_name}にログインします。(数分待つ必要があります。)

.step 7
コンソールに戻って以下のコマンドを実行してください。

サンプルデータを{product_name}に投入します。

```
docker-compose exec api /usr/bin/create_mini_lab.sh
```

NOTE: 実行中にhttpを使用した通信を行います。localhostに対してですが、社内proxyにブロックされた例もありますので、エラーが発生した際はエラー出力の共有とともにご連絡いただければ対処方法を検討いたします。

NOTE: 再度ブラウザに戻り、MSAにログイン後、ダッシュボードに円グラフが二つ追加されていることが確認できればセットアップ完了です。

NOTE: このステップにおいても、環境により、キャッシュクリア/ブラウザ/docker再起動が必要な場合があります。

dockerを再起動する場合は以下の手順をお試しください。

----
docker-compose down
docker-compose up -d
----
