= Quickstart 
:doctype: book
:imagesdir: ./resources/
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:toc: left
:toclevels: 4 

The quickstart covers how you can quickly get started using {product_name} by installing a mini lab.

== Video tutorial
This video details the steps for installing and activating the mini lab.

video::A7zT-AZf2cg[youtube,width=600px,height=360] 

[#prerequisites]
== Prerequisites
The following prerequisites are required for a successful use of {product_name}:
//// 
TODO specify that its for PC and add the specification CPU, RAM,...
////

. A recent version of Git. 
. A working docker and docker-compose setup
* link:https://docs.docker.com/install/[Docker]
* link:https://docs.docker.com/compose/install/[Docker Compose]

include::./doc-src/admin-guide/installation_setup_requirement.adoc[]

////
.Github repository
This guide is composed of a link:https://github.com/ubiqube/quickstart[git repository] which is mainly a set of Dockerfile and docker-compose.xml files to pull the {product_name} from link:https://hub.docker.com/[Dockerhub] 
////

== Mini lab creation

=== Step 1: creation

1. Check your Docker engine has access to DockerHub. You can, for instance, run `docker run hello-world` to test the access.
2. `$ git clone https://github.com/ubiqube/quickstart.git` to clone the GitHub repository on you computer.
3. `$ cd quickstart`
4. `git checkout tags/{revnumber} -b {revnumber}`
5. `$ sudo docker login` (check the note below)
6. `$ sudo docker-compose up -d` to create the mini lab composed of the {product_name} containers.

IMPORTANT: for `docker login`, use the Docker ID "msa2trial" and the link:https://docs.docker.com/docker-hub/access-tokens/[access token] provided by your main point of contact at UBiqube. 

NOTE: If you are already running the {product_name} and wish to upgrade it to a new version check the link:#upgrade[documentation below]

NOTE: The architecture of the mini lab is detailed in this link:../admin-guide/architecture_overview{outfilesuffix}[documentation].

[#step2]
=== Step 2: install the libraries (Microservices, Workflows and Adapters) from github.com/openmsa

```
$ sudo docker-compose exec msa_dev /usr/bin/install_libraries.sh
```

At the end of the script execution, you need to restart the API container and the CoreEngine container:

----
$ sudo docker-compose restart msa_api
$ sudo docker-compose restart msa_sms
----

NOTE: The detail of what is included in the mini lab is available here: link:quickstart_packages{outfilesuffix}[mini lab packages]. 

=== Step 3: provision the mini lab with tenants, managed entities, etc.

The mini lab comes with a Linux container (linux_me / 172.20.0.101) for experimentation.
Credentials for the Linux machine are:

 - username: `msa`
 - password: `ubiqube`

In order to ease your discovery of {product_name}, we are providing a script that will create the mini lab environment for you: 

- 1 tenant - BladeRunner
- 1 subtenant - Tyrell Corporation
- a managed entity to manage the Linux container - linux_me
- some microservices and workflow to start configuring the managed entity - users, firewall, etc.

To create the mini lab environment, run the CLI command from where you have cloned the quickstart Github project:
```
$ sudo docker-compose exec msa_dev /usr/bin/create_mini_lab.sh
```

=== Step 4 (optional): Setting up log aggregation for linux_me
1. `$ sudo docker-compose exec linux_me bash` issue this command from the host machine in order to connect to linux_me.
2. `[root@linux_me /]# echo '*.* @msa_front' > /etc/rsyslog.d/mini_lab.conf` to create rsyslog configuration.
3. `[root@linux_me /]# service rsyslog restart` restart the service.

Now you should start to see device logs for linux_me appearing in the alarm section of the {product_name} portal.

=== Step 5: start using the {product_name}

Browse: link:https://localhost/[] and connect with username `ncroot` and password `ubiqube`. 

== Mini lab detailed description
=== Use case 1: firewall orchestration on Linux

This lab use case will show you in a simple way how you can use {product_name} to automate the configuration of iptables-based firewall policy on the Linux container included in the mini lab.

The development of this use case is detailled in this guide: link:../developer-guide/simple_firewall_policy_mngt{outfilesuffix}[Firewall Policy Automation]

You can use the guide to recreate the use case step by step or you may also directly run the use case with the workflow and microservices that are installed in the mini-lab.

For that, you'll have to select the subtenant named "TYRELL CORPORATION," click on the link "Automation" on the left menu and select the tab "Workflows." The workflow to use is "Simple Firewall (Python)."

video::QRwv78yQWss[youtube,width=600px,height=360]

== Going further with the mini lab
After you have installed and activated the mini lab, here are some tutorials that will allow you to go further with {product_name}.

.Tutorials
These tutorials can be completely executed with the mini lab.

- link:../developer-guide/workflow_getting_started_developing_python{outfilesuffix}[Helloworld Workflow for Python].
- link:../developer-guide/workflow_getting_started_developing_php{outfilesuffix}[Helloworld Workflow for PHP].
- link:../developer-guide/bpm_getting_started_developing{outfilesuffix}[Helloworld BPMP].
- link:../developer-guide/microservices_getting_started_developing{outfilesuffix}[Getting Started with Microservices Design]: design a simple microservice to manage Linux users.
- link:../developer-guide/simple_firewall_policy_mngt{outfilesuffix}[Firewall Policy Orchestration]: design micorservices and workflow to orchestrate firewall policy.

.Demo and use cases
 - link:demo_ansible{outfilesuffix}[Workflow: Ansible playbook runner]
 - link:demo_public_cloud_automation_aws{outfilesuffix}[Workflow: VNF orchestration on AWS]

== Mini lab additional info

[#upgrade]
=== Fresh install or upgrade ?

The quickstart repository is maintained on https://github.com/ubiqube/quickstart and the latest version is available on the branch master.

If you are upgrading your {product_name}, you can either do a clean install for the quickstart by removing your docker containers and the quickstart directory and go to step 2. above or you can update your quickstart with `cd quickstart` and checkout the latest version you want to upgrade to.

NOTE: In case you have updated the {product_name} with `docker-compose up -d` or `docker-compose pull`, you might experience cache issues (for instance, your changes may not be reflected on the UI). To solve that, you can clean your browser cache, or use a browser private session.

=== Upgrade version N to N+1

Starting from version 2.2.0, the quickstart provides an upgrade script `upgrade.sh` for taking care of possible actions such as recreating some volume, executing some database specific updates,...

Let's say that you are running {product_name} version {revnumber-prev}, to upgrade to the version {revnumber}, you need to follow these steps:

1. `$ sudo docker login` (in case you are not authenticated yet)
2. `$ cd quickstart`
3. `$ git checkout master`
4. `$ git pull`
5. `$ git checkout tags/{revnumber} -b {revnumber}`
6. `$ ./scripts/upgrade.sh`

=== Install a specific version

For each release of the {product_name}, there is a tag that you can use if you need to install a specific version of the product.

To install a tagged version, you can checkout the tag and go to the install steps above.

For example, the CLI command below will checkout the quickstart for the release {revnumber}.

`git checkout tags/{revnumber} -b {revnumber}`

The releases and tags are available link:https://github.com/ubiqube/quickstart/releases[here]
