= MSactivator(TM) (MSA) Documentation
ifndef::imagesdir[:imagesdir: images]
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

[cols="3*"] 
|===

a| link:user-guide/manager-guide-single{outfilesuffix}[Manager Guide,window=_blank] link:pdf/user-guide/manager-guide-single.pdf[(pdf),window=_blank] 

a| link:developer-guide/developer-guide-single{outfilesuffix}[Developer Guide,window=_blank] link:pdf/developer-guide/developer-guide-single.pdf[(pdf),window=_blank]

a| link:admin-guide/admin-guide-single{outfilesuffix}[Admin Guide,window=_blank]link:pdf/admin-guide/admin-guide-single.pdf[(pdf),window=_blank]

a| link:release-notes/release_notes{outfilesuffix}[Release Notes,window=_blank]link:pdf/release-notes/release_notes.pdf[(pdf),window=_blank]

a| link:lab-guide/index{outfilesuffix}[Lab Guide,window=_blank]

a| link:community-guide/index{outfilesuffix}[Community Guide,window=_blank]

|===

=== Last releases

[cols="1,1,1"]
|===
|Version|Date|Quickstart reference

|2.8.11
|18/Dec/23
|

|2.8.9.3
|7/Dec/23
|

|2.8.9.2
|3/Nov/23
|https://github.com/ubiqube/quickstart/releases/tag/MSA-2.8.9.2

|
|===
