= Release Notes
:imagesdir: ./resources/
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:doctype: book

== Latest Release 
The latest {product_name} release is 2.0.1. 

The convention works as follows: x.y.z (all representing numbers) and

x = major release (major upgrade of product), 

y = minor release (features, changes)

z = bug or security fixes

== User Experience (UX)

{product_name} introduces a completely new UX empowering the user with a holistic approach to managing a wide range of entities such as firewalls, UTMs, switches, etc. and also managing cloud infrastructure or physical data center assets.

The look and feel of the login page was improved to be more intuitive with navigation and to showcase the capabilities of {product_name}.

Logo designs have been smartly redesigned to have users know which product is being used, in addition to our company logo (Powered By UBiqube) being more prominent.  

Menu layouts reflect alignment to the product vision. Integration and Automation are now top levels of the tree selection on the left-hand side of the dashboard, making it more intuitive to developers of this product.

The functional duality of the {product_name} being an operation platform as well as a development framework provides two navigation environments to address both types of user:

- A developer-centric environment.
- A manager-centric environment.

The {product_name} UX structure is in line with our modular {product_name} architecture (microservices, workflows, etc.) for consistency and greater concept adoption.

The Developer User now features access to three editors which include Microservices, Workflows and BPM from the one screen.

This has allowed opening of all the screens for the Workflow Editor to be able to create processes, tasks and code.

TIP: Go to link:user-guide/gui_overview{outfilesuffix}[GUI overview] to get a detailed description of this new user interface.

== Enhancements

=== Automation: Business Process Modeling (BPM)

The {product_name} Automation stack has been enriched with a business process modeling (BPM) visual workflow editor. 

With BPM, you can express reliable service orchestration, task flows, event handling and apply integrated automation principles through diagrams in more intuitive and visual manner.  This makes automation not only technically executable from the visual workflow editor, yet easy to understand for everyone.

The BPM is part of the Automation engine, which is tighly integrated with the {product_name}.

You can access the Workflows via REST API in order to start process instances, complete tasks and much more. 

TIP: Go to link:user-guide/bpm{outfilesuffix}[GUI overview] to get a detailed description of this new user interface.

=== Container Based Architecture

A container is essentially software that packages up code and all code dependencies so an application can run quickly and reliably from one computing environment to another, abstracting the computer hardware. 

The {product_name} runs on a set of Docker containers. A Docker container image includes everything needed to run an application: code, runtime, system tools, system libraries and settings.

The reason {product_name} is now containerized reflects not only a move in the industry itself, but it allows for much greater scalability and modular design than past iterations of the product.

== Fixes

Various fixes have been made to the product to ensure its continued ability to empower users, ensure a smoother user experience and deliver the value that businesses need in today's environment while being ahead in terms of features, being evergreen and the agility of the {product_name} to grow.

=== Specific Technical Fixes

=== 2.0.0 Fixes

* MSA-7533 [Managed Entity]: list of supported vendors when creating a ME must be filtered
* MSA-7547 [Deployment Setting]: manufacturer and Model returned as UNKNOWNMSA-7533
* MSA-7605 [Deployment Settings] managed entities not being attached
* MSA-7504 [Deployment Setting]: vendor and Model drop down values disappear on performing edit for 2nd time
* MSA-7601 [Deployment Setting]: editing a deployment setting causes deletion of all DS for a customer
* MSA-7124 [Microservices]: extended Parameters inconsistencies
* MSA-7459 [Microservices]: synchronize API to return fetched Objects
* MSA-7116 [Microservices]: keepOnImport loadExtendedParamaterMap has wrong type
* MSA-7027 [Microservices]: issues parsing microservice parser structure
* MSA-7609 [Microservice Editor]: wrong vendor and model displayed when editing Microservice
* MSA-6470 [Workflow]: wf-details does not retrieve the latest workflows
* MSA-7618 [Workflow]: when filtering by Customer, the Workflows still display all workflows assigned to every customer.
* MSA-7526 [Workflow]: execute service API returns 500
* MSA-7115 [API]: some parameters for loadExtendedParamaterMap do not have their type
* MSA-5662 [API]: rest API call to create a manager returns status code 404 on MSA V2
* MSA-7547 Deployment Setting: Manufacturer and Model returned as UNKNOWN
* MSA-7609 [Microservice Editor] Wrong vendor and model displayed when editing Microservice
* MSA-7504 Deployment Setting Vendor and Model drop down values disappear on performing edit for 2nd time a ME must be filtered
* MSA-6997 Microservice: filter is not case sensitive
* MSA-7601 [MSA2] editing a deployment service causes deletion of all DS for a customer
* MSA-7674 2.x: newly created WF can be attached to a customer but not listed in list of customer WF
* MSA-6927 Microservice: Delete API returns 422 Unprocessable Entity

=== 2.0.1 Fixes

* MSA-4389 [API/DB] record user ID at each execution of a process
* MSA-7490 [2.0 UI] issues after updating Deployment settings  
* MSA-7665 2.0 Port - Parameterise the First time change password      
* MSA-7686 [MS 2.x] attach MS to DS if there is no existing DS shows confusing
* MSA-7687 [MS 2.x] when a new MS is created with a space in the name it should be stored with a "_" in place of the space
* MSA-7690 [MS 2.x] Editor has no XPath option for REST MS (config type = XML)
* MSA-7716 [MS] import options not supported  
* MSA-7719 WF + MS variable advanced parameters failing on create / edit.
* MSA-7755 BPM - Cannot trigger update process from BPM      
* MSA-7767 Swagger Doc Update             
* MSA-6841 [UI 2.0] explicit loading of a URL leads to Not Found message        
* MSA-7325 [2.0 UI] Deployment Settings ME not listed (unable to detach it)
* MSA-7429 Creating new customer and attaching WF needs as wildfly restart
* MSA-7648 UBI Context : User password management - force to change password at first login does not appear until clicked on Customer
* MSA-7675 getServiceInstanceOwner does not return allowSchedule in process instance       
* MSA-7715 Port 20.0.0- Parameterise the First time change password - popup
* MSA-7758 Transaction Error on Get Deployment settings API              
* MSA-6609 Microservices console - Text in the confirmation dialog box on deleting the row in MS screen shows huge row names
* MSA-6762 ME create/edit: admin (or at least ncroot) should be able to view the password in clear text                   
* MSA-6793 [ME] ME nature is not editable         
* MSA-7048 Microservice: variable extractors pending API updates       
* MSA-7373 Variable type mismatch between API and XML for worklow           
* MSA-7397 [MSA2] Configurations / create deployment setting : warning label should be made more visible
* MSA-7448 [UI2.0] in deployment settings, the column "Microservices" should be renamed "Microservices & Templates"  
* MSA-7529 Safari - Infinite loop on Automation section - caused by Data format
* MSA-7582 Display boolean values in MS console table body    
* MSA-7607 [MSA2] GUI deployment setting : text label truncated         
* MSA-7619 Workflow instanciate label typo                   
* MSA-7628 [Microservices] Inconsistency between microservice list and microservice detail for vendors and models
* MSA-7629 Regression: User message not displayed when Managed Entity is created or updated                  
* MSA-7661 Selected customer is not reset properly on logout
* MSA-7693 Show task templates when you create a new tas  
* MSA-7808 getMicroserviceObjectDefinition does not return xpath in parser   
* MSA-7517 Put a practical error message on device/v2/apply-config                
* MSA-7518 device/v2/apply-config returns an error after device is successfully updated         
* MSA-7617 label issue on attach customer to workflow dialog popup   
* MSA-7717 A lot of ME configure tabs are blank 
* MSA-7889 Add python template


