= Release Notes
:imagesdir: ./resources/
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:doctype: book

== User Experience (UX)

{product_name} introduces a completely new UX empowering the user with a holistic approach to managing a wide range of entities such as firewalls, UTMs, switches, etc. and also managing cloud infrastructure or physical data center assets.

The look and feel of the login page was improved to be more intuitive with navigation and to showcase the capabilities of {product_name}.

Logo designs have been smartly redesigned to have users know which product is being used, in addition to our company logo (Powered By UBiqube) being more prominent.  

Menu layouts reflect alignment to the product vision. Integration and Automation are now top levels of the tree selection on the left-hand side of the dashboard, making it more intuitive to developers of this product.

The functional duality of the {product_name} being an operation platform as well as a development framework provides two navigation environments to address both types of user:

- A developer-centric environment.
- A manager-centric environment.

The {product_name} UX structure is in line with our modular {product_name} architecture (microservices, workflows, etc.) for consistency and greater concept adoption.

TIP: Go to link:user-guide/gui_overview{outfilesuffix}[GUI overview] to get a detailed description of this new user interface.

== Enhancements

=== Automation: Business Process Modeling (BPM)

The {product_name} Automation stack has been enriched with a business process modeling (BPM) visual workflow editor. 

With BPM, you can express reliable service orchestration, task flows, event handling and apply integrated automation principles through diagrams in more intuitive and visual manner.  This makes automation not only technically executable from the visual workflow editor, yet easy to understand for everyone.

The BPM is part of the Automation engine, which is tighly integrated with the {product_name}.

You can access the Workflows via REST API in order to start process instances, complete tasks and much more. 

TIP: Go to link:user-guide/bpm{outfilesuffix}[GUI overview] to get a detailed description of this new user interface.

=== Container Based Architecture

A container is essentially software that packages up code and all code dependencies so an application can run quickly and reliably from one computing environment to another, abstracting the computer hardware. 

The {product_name} runs on a set of Docker containers. A Docker container image includes everything needed to run an application: code, runtime, system tools, system libraries and settings.

The reason {product_name} is now containerized reflects not only a move in the industry itself, but it allows for much greater scalability and modular design than past iterations of the product.

== Fixes

Page items from various sections of the user interface have been removed to ensure the {product_name} is itself an evergreen product and has the agility to grow.

=== Specific Technical Fixes

* MSA-7533 [Managed Entity]: list of supported vendors when creating a ME must be filtered
* MSA-7547 [Deployment Setting]: Manufacturer and Model returned as UNKNOWNMSA-7533
* MSA-7605 [Deployment Settings] Managed entities not being attached
* MSA-7504 [Deployment Setting]:  Vendor and Model drop down values disappear on performing edit for 2nd time
* MSA-7601 [Deployment Setting]: editing a deployment setting causes deletion of all DS for a customer
* MSA-7124 [Microservices]: Extended Parameters inconsistencies
* MSA-7459 [Microservices]: Synchronize API to return fetched Objects
* MSA-7116 [Microservices]:keepOnImport loadExtendedParamaterMap has wrong type
* MSA-7027 [Microservices]: Issues parsing microservice parser structure
* MSA-7609 [Microservice Editor]: Wrong vendor and model displayed when editing Microservice
* MSA-6470 [Workflow]: wf-details does not retrieve the latest workflows
* MSA-7618 [Workflow]: When filtering by Customer, the Workflows still display all workflows assigned to every customer.
* MSA-7526 [Workflow]: execute service API returns 500
* MSA-7115 [API]: Some parameters for loadExtendedParamaterMap do not have their type
* MSA-5662 [API]: Rest API call to create a manager returns status code 404 on MSA V2

