= Release Notes
:imagesdir: ./resources/
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:doctype: book

IMPORTANT: TODO

== UI / UX

{product_name} introduces a completely new UX bring to the user a holostic aproach to managing a wide range of entities such as firewall, UTM, switches,... but also managing cloud infrastructure or physical data center assets.

The functional duality of the {product_name} being a operation platform as well as a developement framwework provides two navigation environments to address both types of user:
- A developer-centric environment.
- An end-user-centric environment.

The {product_name} UX structure is in line with our modular {product_name} architecure (microservices, workflows, etc.) for consistency and greater concept adoption.

TIP: Go to link:user-guide/gui_overview{outfilesuffix}[GUI overview] to get a detailed description of this new user interface.

== Automation: Business Process Modeling

The {product_name} Automation stack has been enriched with a BPMN workflow engine. 
With BPMN, you can express reliable service orchestration, human task flows, event handling and much more in diagrams that are technically executable yet easy to understand for everyone.
The BPMN engine is tighly integrated with the MSA

You can access the Workflow Engine via REST in order to start process instances, complete tasks and much more. 


TIP: Go to link:user-guide/bpm{outfilesuffix}[GUI overview] to get a detailed description of this new user interface.


== Container Based Architecture



== OS Upgrade to Centos 7.5

The {product_name} now runs on Centos 7.5 making it more secure and protected again vulnerabilities.


