= Release Notes
:imagesdir: ./resources/
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:doctype: book

== User Experience (UX)

{product_name} introduces a completely new UX empowering the user with a holistic approach to managing a wide range of entities such as firewalls, UTMs, switches, etc. and also managing cloud infrastructure or physical data center assets.

The functional duality of the {product_name} being an operation platform as well as a development framework provides two navigation environments to address both types of user:

- A developer-centric environment.
- An end-user-centric environment.

The {product_name} UX structure is in line with our modular {product_name} architecture (microservices, workflows, etc.) for consistency and greater concept adoption.

TIP: Go to link:user-guide/gui_overview{outfilesuffix}[GUI overview] to get a detailed description of this new user interface.

== Automation: Business Process Modeling (BPM)

The {product_name} Automation stack has been enriched with a business process modeling (BPM) visual workflow editor. 

With BPM, you can express reliable service orchestration, task flows, event handling and apply integrated automation principles through diagrams in more intuitive and visual manner.  This make automation not only technically executable from the visual workflow editor, yet easy to understand for everyone.

The BPM is part of the Automation engine, which is tighly integrated with the {product_name}.

You can access the Workflows via REST API in order to start process instances, complete tasks and much more. 


TIP: Go to link:user-guide/bpm{outfilesuffix}[GUI overview] to get a detailed description of this new user interface.


== Container Based Architecture

A container is essentially software that packages up code and all code dependencies so an application can run quickly and reliably from one computing environment to another, abstracting the computer hardware. 

The {product_name} runs on a set of Docker containers. A Docker container image includes everything needed to run an application: code, runtime, system tools, system libraries and settings.

The reason {product_name} is now containerized reflects not only a move in the industry itself, but it allows for much greater scalability and modular design than past iterations of the product.

