= User Administration
:toc: left
:toc-title: Content
:imagesdir: ../resources/
:ext-relative: adoc

== Security and Credential Management

=== User Account Locking

Set a global account locking policy for users.

Use the
link:../Support%20and%20Maintenance/cli-configuration-tool.adoc[MSActivator
CLI based configuration] at Web Portal configuration → Advanced
Configuration to set the number of accepted login failures and the
duration of the account lock.

=== User Password Expiration

Set a global password expiration policy and enforce user password
updates on a regular basis.

Use the
link:../Support%20and%20Maintenance/cli-configuration-tool.adoc[MSActivator
CLI based configuration] at JEntreprise configuration → General
Configuration to set the user password validity in days.

=== User Password Policy

By default the password strength is not enforced in the customer portal
but it's possible to define specific rules by customising the file
CustomerBoardContent under /opt/ses/WebContent/operators//content/

By default, no specific password policy is used:

....
password.use.specific.policy=0
          
....

but this can be enabled by setting the value to 1.

....
password.use.specific.policy=1
password.min.characters=8
password.min.lowercase=1
password.min.uppercase=1
password.min.digit=1
# Punctuation or special character among ^'<>{}"/|;:.,~!?@#$%^=&*]()[_+
password.min.specials=1
          
....

Once configured, the policy can be applied by restarting the portal.

....
service tomcat restart
          
....

==== Customization

The same configuration is available for a customized portal.

=== Password Recovery

Users who have forgotten their password can request a new one and get
access to their account.

[.confluence-information-macro-icon]#__#

The password recovery can only work if the user has provided a valid
email in his profile and if the MSActivator has been properly configured
to send email (see
link:../Administration/Installation%20and%20Configuration/msactivator-installation-and-configuration-guide.adoc[MSActivator
Installation and Configuration Guide]).

==== Login page

On the login page, available on custom UBI, click on "Forgot my
password"

==== Support in a new customization

To enable password recovery for a new custom portal, the lines below
should be included in Connection.jsp

....
<script type="text/javascript" src="<%= request.getContextPath() %>/script/prototype/prototype.js" ></script>
....

....
<script type="text/javascript" src="<%= request.getContextPath() %>/script/ses/util.js" ></script>
....

....
<script type="text/javascript" src="<%= request.getContextPath() %>/script/ses/resetPassword.js" ></script>
....

Create an HTML label with an onClick event. User login should be passed
as a parameter.

....
<label style="cursor:pointer;font-size: 12px;" onClick="resetPassword('<%= request.getContextPath() %>', document.getElementById('login_uname'));">Forgot Password ?</label>
....

Add an HTML div to display a message that confirms that a mail was sent
to the user. The div id should be "resetPasswordMsg.

....
<div id="resetPasswordMsg" style="display: none;"><font style="font-family:Verdana,sans-serif;font-size:10pt;" >A mail associated to this account has been sent to confirm your request</font></div>
....
