= Version 2.1
:imagesdir: ./resources/
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:doctype: book
:toc: left
:toclevels: 4 

Various fixes have been made to the product to ensure its continued ability to empower users, ensure a smoother user experience and deliver the value that businesses need in today's environment while being ahead in terms of features, being evergreen and the agility of the {product_name} to grow.

== New features

The following feature improvements are included with this release:

=== Assurance

Assurance (partially implemented in RC2) protects against and manages risk. This release renders the logs from Elasticsearch that are collected from managed entities.  This will enable you to better manage risk and determine best courses of action, based on the data.  

For now this is disabled by default and not completely full assurance, but you can enable this feature for preview via the “FEATURE_ALARMS=true” flag in your docker-compose.yml file.

=== User and Tenant Management (UI and REST API) 

User and tenant management screens are now enabled by default.  This is designed to improve the customer experience.

=== Product License Management

Licensing is now easier to maintain.  It is displayed, along with the ability to activate it via the settings screen.

=== Workflow

Workflow task templates (basic code templates for PHP and Python tasks) are now included in the editor.

=== Microservice

The Microservice reference type has been added to the Workflow editor as an advanced type.

=== REST API

REST API connection status - the portal UI now handles issues connecting to the MSA REST API more eloquently, for example by displaying feedback messages to the end user until the MSA REST API is online and connected.

Swagger has improved REST API documentation.


== CoreEngine
No changes have been made to the core engine from previous versions of the product. This allows consistency from branches of OpenMSA (community version), found on GitHub: https://github.com/openmsa

== Upgrading
Instructions to upgrade are here: https://ubiqube.com/wp-content/docs/latest/admin-guide/upgrade.html

== Notes

The legacy portal “UBI/en” is now deprecated. UBiqube will not maintain it or provide any support related to this portal. 

== Specific technical fixes

=== 2.1.0 rc1 (release candidate 1)

==== Bug fixes

* MSA-7855 : [Microservices] synchronize API v2 not triggering any action on SecEngine
* MSA-7459 : [Microservices] synchronize API to return fetched Objects
* MSA-7970 : [Microservices] configuration parser: correspondence for multiple regexp
* MSA-7801 : [Microservices] list view vs details view API data inconsistency
* MSA-7801 : [Microservices] list view vs details view API data inconsistency
* MSA-7628 : [Microservices] Inconsistency between microservice list and microservice detail for vendors and models
* MSA-8004 : [Microservices] vendor/model is not being saved when creating a new microservice
* MSA-8015 : [API] DeviceRS form fields - get default fields for Custom Device adapters
* MSA-7835 : [API] getMicroserviceObjectDefinition does not return multiple regexp under array
* MSA-7830 : [API] managed entity create and edit API doesn't accept all values
* MSA-7882 : [API] Swagger doc update for remaining RS
* MSA-8153 : [API] Update-device-update-device-data-in-ES-only
* MSA-8154 : [Workflow] Service Instance Count differs in Services List view and Instances view	
* MSA-8128 : [Workflow] Saving Workflow Causes NullPointerException
* MSA-8123 : [Workflow] Duplicates in last executed processes in Dashboard
* MSA-8194 : [Workflow] Existing pingME Python WF not working since upgrading to 2.1.0rc1
* MSA-8009 : [Packaging] Adapt Variables Extended Parameter API for API Container


=== 2.1.0 rc2 (release candidate 2)

==== Features

* MSA-8291 : [UI]: Show API connection status on UI
* MSA-7693 : [Workflow] Show task templates when you create a new task
* MSA-8292 : [Workflow] Make it possible to create/edit an OBMFRef variable including advanced parameters
* MSA-6908 : [API] Update sql query in UserDao getManagerRole with additional check
* MSA-7915 : [API] Swagger Doc Update - DeviceRS
* MSA-7946 : [API] License Management - API to upload a License
* MSA-7947 : [API] License Management - API to read the license info
* MSA-7949 : [API] User Management - API to attach and detach subtenant to manager by Id
* MSA-8251 : [Configuration] DB tables for MSA VARS
* MSA-8357 : [Admin] fuzzy search and lastModified field for list Admin

==== Bug fixes

* MSA-7698 : [Microservice] Optional parameters (hostname, management port interface etc.) are not saved.
* MSA-8068 : [Microservice] When object_id = 0 the microservice is impossible to delete
* MSA-8311 : [Microservice] Some data not displaying in the table in the console
* MSA-8344 : [API] Manage alarm manage API bug fixes
* MSA-8356 : [API] Manager API doesn't save pwd, autofills prefix prefix with default NCL value, doesn't accept updated tenant ID
* MSA-8211 : [API] Remove buggy synchronization API from DeviceRS
* MSA-8024 : [API] it is not possible anymore to create Manager by API (classic portal)
* MSA-8053 : [API] User Mgmt: general issues
* MSA-8191 : [API] Search logs API not working
* MSA-8128 : [Workflow] Saving a workflow Causes NullPointerException
* MSA-8154 : [Workflow] Service Instance count differs in services list view and Instances view
* MSA-8198 : [Workflow] cannot save workflows
* MSA-8280 : [Workflow] editing an existing workflow (created using legacy UI) and saving will make it invisible in legacy GUI
* MSA-8288 : [Workflow] Workflow API does not return supported language for lists
* MSA-7908 : [Auth] user locked out of UI due to exception on wildfly (related to repository)
* MSA-7868 : [Admin] after login, the tenant is already assigned
* MSA-8236 : [Admin] User management for ncroot need review
* MSA-8260 : [Admin] when connected as a manager the selected tenant is not displayed
* MSA-8268 : [Admin] Set tenant for manager on login
* MSA-8289 : [Admin] tenant Ubiqube/NCL should be hidden from the UI
* MSA-8241 : [Admin] Edit Subtenant throwing NPE on further edits
* MSA-6859 : [Admin] When a customer is selected in the breadcrumb, the related tenant is not displayed
* MSA-8214 : [Adapter] Not able to find Netconf MS definitions in DS
* MSA-8259 : [Adapter] Not able to see Netconf model for Oneaccess in the UII
 
