= Version 2.2
:imagesdir: ./resources/
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:doctype: book
:toc: left
:toclevels: 4 

Various fixes have been made to the product to ensure its continued ability to empower users, ensure a smoother user experience and deliver the value that businesses need in today's environment while being ahead in terms of features, being evergreen and the agility of the {product_name} to grow.

== New features

The following feature improvements are included with this release:

=== Topology

The {product_name} link:../user-guide/managed_entities_topology{outfilesuffix}[topology] will allow you to display a graphical view of your network based on various criteria.

The topology will give insight into how your network, domain and entities are structured and interconnected. You can zoom in and out on particular aspects of the topology view, as well as find out relevant information about managed entities under your control.

In addition, you will be able to build you own topology to suit your specific requirements. By default a Layer 3 topology is available based on SNMP requests to get the network data of your managed entities.

=== BPM

The {product_name} BPM link:../user-guide/bpm{outfilesuffix}[execution console] provides a simple and comprehensive UI to track the execution of your BPM processes in real time.

The BPM link:../developer-guide/bpm_editor{outfilesuffix}[editor] has an extended coverage of the BPMN 2.0 standard with the addition of decision gateways as well as additional control over the execution flow of your BPM processes.

=== Microservices

The support for additional variable types has been added to help you design user-friendly link:../developer-guide/microservice_variables{outfilesuffix}[microservices] and provide extended abstraction possibilities.

=== Workflows

The support for additional variable types has been added to help you design user-friendly link:../developer-guide/workflow_editor{outfilesuffix}[workflows] and provide an enhanced integrated experience with your microservices.


=== Assurance

Assurance protects against and mitigates risk. This release renders the logs from Elasticsearch that are collected from managed entities.  This will enable you to better manage risk and determine the best courses of action, based on the available data.  

You will be able to create and manage your own librairies of alarms and decide if an alarm will trigger an automated process or simply send a notification, or both.

== CoreEngine

No changes have been made to the core engine from previous versions of the product. This allows consistency from branches of OpenMSA (community version), found on GitHub: https://github.com/openmsa

== Upgrading

Instructions to upgrade are here: link:../user-guide/quickstart{outfilesuffix}#upgrade[upgrade guide]

=== Specific instruction for upgrating from 2.1.0GA to 2.2.0GA

Starting from version 2.2.0, the quickstart provides an upgrade script `upgrade.sh` for taking care of possible actions such as recreating some volume, executing some database specific updates,...

Let's say that you are running {product_name} version {revnumber-prev}, to upgrade to the version {revnumber}, you need to follow these steps:

1. `$ sudo docker login` (in case you are not authenticated yet)
2. `$ cd quickstart`
3. `$ git checkout master`
4. `$ git pull`
5. `$ git checkout tags/{revnumber} -b {revnumber}`
6. `$ ./scripts/upgrade.sh`

== Specific technical fixes and feature details

=== 2.2.0 GA

TODO: add JIRA

==== Features

==== Bug fixes

==== Known issues
