= Version 2.8.7
:front-cover-image: image:release-notes-front-cover-2.8.7.pdf[]
:toc: left
:toclevels: 3
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
ifndef::imagesdir[:imagesdir: images]

//OK HTML 
ifdef::html[]
:includedir: doc-src/release-notes
endif::[]

// OK PDF
ifdef::pdf[]
:includedir: .
endif::[]

Welcome to the 2.8.7 release of the {product_name}. There are many updates in this version that we hope you'll like, some of the key highlights include:


== UX and Navigation

== Framework


=== CoreEngine

== Upgrade

Instructions to upgrade available in the https://ubiqube.com/wp-content/docs/latest/user-guide/quickstart.html[quickstart].

=== Specific instructions for upgrading to 2.8.7

The quickstart provides an upgrade script `upgrade.sh` for taking care of possible actions such as recreating some volume, executing some database specific updates,...

In order to upgrade to the latest version, you need to follow these steps:

1. `cd quickstart`
2. `git checkout master`
3. `git pull`
4. `./scripts/install.sh`

== Specific technical fixes and feature details

=== Features

=== Bug fixes