= Version 2.8.6
:front-cover-image: image:release-notes-front-cover-2.8.6.pdf[]
:toc: left
:toclevels: 3
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
ifndef::imagesdir[:imagesdir: images]

//OK HTML 
ifdef::html[]
:includedir: doc-src/release-notes
endif::[]

// OK PDF
ifdef::pdf[]
:includedir: .
endif::[]

Welcome to the 2.8.6 release of the {product_name}. There are many updates in this version that we hope you'll like, some of the key highlights include:

- Manager Dashboard: quickly navigate from the manager dashboard to the managed entities or the alarms.
- Manager Dashboard: add a new alarm dashboard component to enhance you data visibility
- Assurance: load vendor specific MIB in the repository and translate SNMP trap OID to clear messages

== Microservices

== Managed Entities

== Framework

=== CoreEngine

No changes have been made to the core engine from previous versions of the product. This allows consistency from branches of {openmsa_name} (community version), found on GitHub: https://github.com/openmsa

== Upgrade

Instructions to upgrade available in the https://ubiqube.com/wp-content/docs/latest/user-guide/quickstart.html[quickstart].

=== Specific instructions for upgrading to 2.8.6

The quickstart provides an upgrade script `upgrade.sh` for taking care of possible actions such as recreating some volume, executing some database specific updates,...

In order to upgrade to the latest version, you need to follow these steps:

1. `cd quickstart`
2. `git checkout master`
3. `git pull`
4. `./scripts/install.sh`

== Specific technical fixes and feature details

=== Features

* MSA-12238 - [Alarms] alarm management should be accessible from left menu
* MSA-12244 - [Alarms] create alarm based on search results
* MSA-12267 - [Alarms] in alarm condition, improve managed entity/tenant/subtenant selection
* MSA-12368 - [Alarms] add navigation link from alarm to managed entity
* MSA-12410 - [Alarms] add navigation link from alarms to managed entity
* MSA-12326 - [API] [Microservices] add variable configuration option to display a variable in either create or edit or both
* MSA-10983 - [Assurance] export SNMP Reports to be downloaded as PDF files
* MSA-12222 - [Assurance] in alarm page and log page: add column for ip address,managed entity name and tenant Id
* MSA-12310 - [Assurance] add managed entity name column in log tab
* MSA-12311 - [Assurance] add managed entity name and management IP in log and alarm tabs
* MSA-12353 - [Assurance] alarms/Logs filtering enhancement
* MSA-12355 - [Assurance] dynamic SNMP trap translation
* MSA-12373 - [Assurance] list managed entities based on status
* MSA-12298 - [Audit] audit logs need more details like managed entity, profile,... ID
* MSA-11916 - [CoreEngine] stream daemon logs (smsd,polld,...) to stdout and make them available with docker logs
* MSA-12357 - [Dashboard] improve dashboard navigation and data visibility
* MSA-12372 - [Dashboard] add Alarm list as a manager dashboard component
* MSA-12193 - [HA] need to be able to support multiple alarmd services/replicas on Swarm deployment
* MSA-12262 - [JWT] enable JWT Expiration check
* MSA-12442 - [Logs] add navigation link from logs to managed entity
* MSA-12354 - [Manager dashboard] cursor click to status should lead to a list of the ME filtered by status
* MSA-11975 - [Topology] topology workflow is not supporting SNMPv3
* MSA-12318 - [Topology] new API to return topology instance data based on serviceId
* MSA-12306 - [UI] performance: Synchronization Time

=== Bug fixes

* MSA-12078 - [Alarm] review elasticsearch query generation in check_alert.php for better maintenance
* MSA-12393 - [API] API to ping IP/FQDN doesnt work in MSAv2
* MSA-12219 - [API/Workflow] composite Array variable field name malformation when value is empty after run time
* MSA-12220 - [API/Workflow] workflow Instance still running if you put one bad character in the context, the instance never stop
* MSA-12322 - [Assurance] rsyslogd isn't relaying the syslog received and eats 100% of CPU - Investigation
* MSA-12236 - [BPM/Workflow] Variables has been updated When you do, the contents of the context are throwback.
* MSA-12241 - [BPM] It is NG to get the setting file list of the Japanese file name
* MSA-12252 - [BPM] If you update the value of context from the BPM side when there is a key with only numbers in context, Internal data goes wrong
* MSA-12044 - [CoreEngine] Alarms failing to be written in ES must be submitted again via one load_alarms mechanism similar to load_logs
* MSA-12398 - [CoreEngine] The snmp, sshd and rsyslog services must not be launched in docker-entrypoint.sh but Dockerfile
* MSA-12124 - [Logs] in the log tab (and same in the alarm) the rawlog in the minimized view is different from the detailed view
* MSA-12091 - [Managed Entity] when created as Monitoring Generic the UI shows a traffic graph
* MSA-12119 - [Microservices] import _order is not working properly while sorting with more than 2 pages
* MSA-12232 - [Microservices] timeline of log confirmation is disjointed (previously always in order)
* MSA-12295 - [Microservices] composite array variables display/hide not consistent
* MSA-12296 - [Microservices] command_call option 2 not working anymore
* MSA-12403 - [Microservices] Sorting on MS column values is broken
* MSA-12430 - [Microservices] Vanishing Data in DB on Inventory Device
* MSA-12330 - [UI] Can't see the command launched after MSA setting variable modification