= Version 2.8
ifndef::imagesdir[:imagesdir: images]
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


The focus of the 2.8.0 release of {product_name} is mainly about improving the performances and reliability. 

The Microservice console has also been improved to provide a better user experience by allowing bulk changes of the microservice instances as well as additional design features. Advanced parameters have also been improved for a better support of the variables.


== CoreEngine

No changes have been made to the core engine from previous versions of the product. This allows consistency from branches of OpenMSA (community version), found on GitHub: https://github.com/openmsa

== New Libraries Available

=== Adapters

== Upgrading

Instructions to upgrade available in the quickstart guide.

=== Specific instructions for upgrading from {revnumber-prev} to {revnumber}

Starting from version 2.2.0, the quickstart provides an upgrade script `upgrade.sh` for taking care of possible actions such as recreating some volume, executing some database specific updates,...

Let's say that you are running {product_name} version {revnumber-prev}, to upgrade to the version {revnumber}, you need to follow these steps:

1. `cd quickstart`
2. `git checkout master`
3. `git pull`
4. `./scripts/install.sh`

=== only from 2.4.x or earlier

1. `docker-compose exec msa_front /bin/sh -c 'chown -R nginx:nginx /etc/ssl'`

== Specific technical fixes and feature details

=== 2.8.0 GA

==== Features

* MSA-11107 - [DB] Replace PostgreSQL standalone for PostgreSQL cluster
* MSA-10831 - [CoreEngine] MIB Translation, MIB compiler
* MSA-10832 - [CoreEngine] MIB Translation,Translation rules creation Workflow
* MSA-10833 - [CoreEngine] MIB Translation, syslogd configuration generator
* MSA-10834 - [CoreEngine] MIB Translation, Modify sms_syslogd daemon code
* MSA-11123 - [Logs] - Elasticsearch with double indexing
* MSA-10097 - [Microservice] Microservices instance order isn't correct in MSA UI after an "apply configuration" if the Microservice ordering is recalculated during the post import
* MSA-10707 - [Microservice/Workflow] Enable more advanced parameters
* MSA-10862 - [Microservice] Data Retention Versatility 2 Bulk operation on Microservice console
* MSA-10888 - [Microservice] Search and Filter Microservice Object per column
* MSA-11139 - [Microservice] Microservice Identifier Extractor regex optimisation
* MSA-10755 - [Workflow] Filter with category 2

==== Bug fixes

* MSA-11104 - [Adapter] connection to IOS XR fails if there is a banner after login to device
* MSA-11083 - [Adapter] Cisco XR adapter: when conf commit fails is not showing the error details in smsd.log
* MSA-10828 - [DB] table redone.contact not cleaned
* MSA-10570 - [Managed Entity] Api does not return the right total number of subtenants in the device
* MSA-10643 - [Microservice] use of type Microservice Reference for a Composite is not working
* MSA-10844 - [Microservice] Constraint buffer isn't returned in the UI
* MSA-11113 - [Microservice] 504 Gateway Timeout on loading large MS instance list
* MSA-11035 - [REST API Adaptor] - delete operation bug & success response processing problem
* MSA-11013 - [UI] Microservice _order variable should be taking into account on MSA UI side to order properly the MS instances
* MSA-11098 - [Workflow] performance issue when selecting details or History or trying to call an update process
* MSA-10481 - [Workflow] Executing WF process with only WF file(.xml) name throwing NPE instead of proper error message
