= Version 2.7
ifndef::imagesdir[:imagesdir: images]
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


The focus of the 2.7.0 release of {product_name} is on enhancements to our MANO support, improved security, and new libraries for inventory management.

In addition to these enhancements, we have made a number of quality fixes and user experience improvements, please see below the details.

We hope you enjoy this release, and encourage you to upgrade to avail of all of the improvements listed below.

== LDAP Secured

-  already integrated with LDAP for user auth, but now with version 2.7 we have added support for LDAP Secured (LDAPS), specifically we tested against the OpenLDAP provider but other providers should also work fine.

== MANO backend support

We have made a number of improvements to the MANO support in  -  for version 2.7, including the following enhancements:

- Migrating our MANO database to PostgreSQL for improved storage performance.
- Integration of our MANO module into our overall HA architecture in  - , to enable MANO support to scale with the rest of MSAactivator in HA deployments.
- Implementation of the Network Service (NS) instance scale-out and scale-in operations.
- Implementation of the enhance NS LCM workflow to address scale-out and scale-in of NS instance.
- Implementation of the enhance NS LCM workflow to address automatic scaling of NS instance.
- Implementation of the enhance NS LCM workflow to create the VNF LCM service instance of each VNF instance part of the NS.
- Implementation of the enhance VNF LCM workflow to address automatic scaling of VNF instance.
- Implementation of the enhance VNF LCM workflow to implement Software upgrade for VNFs.

== Category for topology

In the Topology view of {product_name}, the user can now assign arbitrary categories to their managed entities, and then filter the list of managed entities displayed on the Topology based on the selected, user-defined, category. 
This gives the end user a lot of flexibility in determining how their topologies are displayed.

New text area for WF variable

We have added a new larger text area to the workflow console, to enable the workflow designer to display larger bodies of text in the console more comfortably, including the ability to display the content of a text file in that new text area.

== Security - Log4J fix

Due to the recent widely-publicized security vulnerabilities in the Log4J library, we have reviewed all of our usage of Log4J in {product_name} 2.7 and upgraded those dependencies to the latest version of Log4J.

== OST upgrades

In addition to the Log4J upgrades mentioned previously we have also made a number of open source library upgrades including:

- Added support for SNMPv3 to our SMS service.
- Upgraded ODBC versions used on SMS to postgresql12-odbc and unixODBC-2.3.9.
- Added zip and unzip to SMS to support the integration of Cisco FTD.

== Resource Inventory Management

In {product_name} 2.7, we have added microservices and workflows for managing resources inventory, which give the capability for the user to create and control the use of any type of resources for any use case.

Available microservices and workflows concern 5 items :

- IP Pool Management
- VLAN Pool Management
- vPC (virtual port channel) Pool Management
- VNI (VxLAN Identifier) Pool Management
- ASN (Autonomous Systems Numbers) Pool Management


== CoreEngine

No changes have been made to the core engine from previous versions of the product. This allows consistency from branches of OpenMSA (community version), found on GitHub: https://github.com/openmsa

== New Libraries Available

=== Adapters

== Upgrading

Instructions to upgrade available in the quickstart guide.

=== Specific instructions for upgrading from {revnumber-prev} to {revnumber}

Starting from version 2.2.0, the quickstart provides an upgrade script `upgrade.sh` for taking care of possible actions such as recreating some volume, executing some database specific updates,...

Let's say that you are running {product_name} version {revnumber-prev}, to upgrade to the version {revnumber}, you need to follow these steps:

1. `cd quickstart`
2. `git checkout master`
3. `git fetch --unshallow`
4. `git pull`
5. `./scripts/install.sh`

=== only from 2.4.x or earlier

1. `docker-compose exec msa_front /bin/sh -c 'chown -R nginx:nginx /etc/ssl'`

== Specific technical fixes and feature details

=== 2.7.0 GA

==== Features

`* MSA-10663 - [Security] Node JS upgrade

==== Bug fixes

* MSA-10552 - [Admin] tenant deletion using API not removing association of WF with subtenant (now non-existing)
* MSA-10567 - [Adapter] asset events are not indexed in Elasticsearch
* MSA-10659 - [API] connection leak due to MS pagination (MSA-10638)
* MSA-10571 - [Backend] implement restart of API container if exited
* MSA-10177 - [Dashboard] instance Link from History
* MSA-9893 - [HA] Syslogs are not redirected from front to CoreEngine (msa-sms) containers
* MSA-10519 - [HA] HA-migration failed on (Restore Device Interface settings for first uni)
* MSA-10599 - [Managed Entity] total count is not filtered
* MSA-10616 - [Managed Entity] wrong value of total number of Managed Entity after filtering by Tenant
* MSA-10627 - [Managed Entity] create Managed Entity screen throws error when you switching between sections
* MSA-10641 - [Managed Entity] filtering Adapter does not work with particular term
* MSA-10661 - [Managed Entity] ellipsis Variable value
* MSA-10662 - [Microservice] get repositories with List of String and store it in XML
* MSA-10679 - [Microservice] variables for created Microservice are always displayed as "Readonly variables"
* MSA-10727 - [Microservice] missing "add array variable extractor set" within an array after saving the Microservice
* MSA-10854 - [Microservice] UI - Bad JSON during create of a new instance of Microservice
* MSA-10855 - [Microservice] unable to edit Import in MS created with XML type
* MSA-10865 - [Microservice] bad JSON during delete of an instance of Microservice
* MSA-10992 - [Microservice] unauthorized Microservice reference
* MSA-10703 - [Permissions] intent based : issues with "create" right
* MSA-10700 - [Python SDK] msa_sdk doc is showing wrong class variable for task execution status
* MSA-10926 - [Quickstart] conflict during upgrade if another stack is deployed on HA
* MSA-10561 - [Security] new vulnerabilities detected in 2.6 GA
* MSA-10782 - [Security] Log4j patch
* MSA-10199 - [UI] orchestration parameters are not full context.
* MSA-10458 - [Workflow] return subtenant and service id for history
* MSA-10490 - [Workflow] select Box shows empty default value but the value is actually set
* MSA-10508 - [Workflow] reusing existing task causes issues when the task is deleted
* MSA-10664 - [Workflow] disable deleting Task when it's linked to the other tasks

=== 2.7.1 Patch

==== Features

* MSA-9811 - [SDK] Update msa_sdk_doc using actions for changes on python sdk
* MSA-11031 - [Free Trial] user registration not working (v2.4.1)

==== Bug fixes

* MSA-6681 - [Alarm Management] check alert issue for automatic operation triggering
* MSA-10850 - [Alarm] Only one alarm is created if several events are managed at the same time by check_alert
* MSA-11012 - [Assurance] Support for SNMP v3 for SNMP based monitoring in MSA2.X
* MSA-11024 - [HA] /opt/sms/logs directory is shared by all sms/alarm containers and the log files are overwritten
* MSA-10712 - [Log Analytic] Logs details not available on small window
* MSA-10843 - [Microservice] Smarty function "sortby" is using a deprecated PHP function "create_function"
* MSA-10711 - [Repository] Not possible to remove an MS because still attached...to a ghost subtenant/DS
* MSA-11002 - [UX] WF user form layout not balanced when using array of variables with multiple keys
* MSA-11029 - [Workflow] perfomance issue when loading several instances with large context
* MSA-11033 - [Workflow][UI] perfomance issue when loading several instances with large context
