= Version 2.2
:imagesdir: ./resources/
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:doctype: book
:toc: left
:toclevels: 4 

Various fixes have been made to the product to ensure its continued ability to empower users, ensure a smoother user experience and deliver the value that businesses need in today's environment while being ahead in terms of features, being evergreen and the agility of the {product_name} to grow.

== New features

The following feature improvements are included with this release:

=== Topology

The {product_name} link:../user-guide/managed_entities_topology{outfilesuffix}[topology] will allow you to display a graphical view of your network based on various criteria.

The topology will give insight into how your network, domain and entities are structured and interconnected. You can zoom in and out on particular aspects of the topology view, as well as find out relevant information about managed entities under your control.

In addition, you will be able to build you own topology to suit your specific requirements. By default a Layer 3 topology is available based on SNMP requests to get the network data of your managed entities.

=== BPM

The {product_name} BPM link:../user-guide/bpm{outfilesuffix}[execution console] provides a simple and comprehensive UI to track the execution of your BPM processes in real time.

The BPM link:../developer-guide/bpm_editor{outfilesuffix}[editor] has an extended coverage of the BPMN 2.0 standard with the addition of decision gateways as well as additional control over the execution flow of your BPM processes.

=== Microservices

The support for additional variable types has been added to help you design user-friendly link:../developer-guide/microservice_variables{outfilesuffix}[microservices] and provide extended abstraction possibilities.

=== Workflows

The support for additional variable types has been added to help you design user-friendly link:../developer-guide/workflow_editor{outfilesuffix}[workflows] and provide an enhanced integrated experience with your microservices.

=== Assurance

Assurance protects against and mitigates risk. This release renders the logs from Elasticsearch that are collected from managed entities.  This will enable you to better manage risk and determine the best courses of action, based on the available data.  

You will be able to create and manage your own librairies of alarms and decide if an alarm will trigger an automated process or simply send a notification, or both.

== CoreEngine

No changes have been made to the core engine from previous versions of the product. This allows consistency from branches of OpenMSA (community version), found on GitHub: https://github.com/openmsa

== Upgrading

Instructions to upgrade are here: link:../user-guide/quickstart{outfilesuffix}#upgrade[upgrade guide]

=== Specific instruction for upgrating from 2.1.0GA to 2.2.0GA

Starting from version 2.2.0, the quickstart provides an upgrade script `upgrade.sh` for taking care of possible actions such as recreating some volume, executing some database specific updates,...

Let's say that you are running {product_name} version {revnumber-prev}, to upgrade to the version {revnumber}, you need to follow these steps:

1. `$ sudo docker login` (in case you are not authenticated yet)
2. `$ cd quickstart`
3. `$ git checkout master`
4. `$ git pull`
5. `$ git checkout tags/{revnumber} -b {revnumber}`
6. `$ ./scripts/upgrade.sh`

==== Migrate your BPM from {revnumber-prev} to {revnumber} ====

With the introduction of decision gateways and other bug fixes, the format of BPM has been updated. If you have created a BPM in {revnumber-prev}, you need to follow those operations:

- In the BPM console, **edit your BPM file**

- For each task, **select again your workflow, process and parameters** you want to execute

- **Save and execute your BPM**

== Specific technical fixes and feature details

=== 2.2.0 GA

==== Features

* MSA-8388 - [UI/Search] Enhancement of the search UI to retrieve MS,WF and BPM + multitenancy + redirect to the selected element
* MSA-8403 - [API/Doc] Swagger doc update - DeviceRS modification
* MSA-8440 - [Workflow] Alarm based workflow execution
* MSA-8527 - [Microservice] Microservice reference type advanced parameters for MS and WF
* MSA-8583 - [Upgrade] image manager to efficiently manage docker images on the host
* MSA-8632 - [Container] Set same uid and gid for users in containers
* MSA-8635 - [API] new API to read the Topology data for a given customer
* MSA-8689 - [Workflow] Camunda external task workers - implementation
* MSA-8692 - [API] API to retrieve microserviceReference data at runtime
* MSA-8722 - [Workflow] Stop or pause the workflow
* MSA-8775 - [API] API call to include latest alarms numbers + list of alarm generated
* MSA-8776 - [API] Alarms enhancement: last execution time, pagination,...
* MSA-8795 - [UI/UX] Rename"integration" to "infrastructure" on the manager UI
* MSA-8828 - [Microservice] Show only in edit view' variable option lacks in microservice UI
* MSA-8831 - [Microservice] There is no option to know the microservice filename to make reference to in the UI
* MSA-8840 - [API] License - restrict to only one in database
* MSA-8842 - [API] Remove vendor and models properties delivered default by api-container
* MSA-8843 - [HA] Make sure alarm generations are not duplicated
* MSA-8844 - [Workflow] Create topology without WF, add legends
* MSA-8854 - [BPM] Implementation of execution tracking
* MSA-8858 - [Workflow/API] Create API to activate the topology
* MSA-8864 - [BPM] execute process by reference and add API to get status by process external reference
* MSA-8880 - [API] Adapt the configurationObjects endpoint for API change
* MSA-8937 - [Workflow/BPM] Workflow task status in the BPM variable
* MSA-9005 - [API] API to detach mulitple subtenant from workflow
* MSA-9010 - [BPM] Decision gateway enhancement
* MSA-9014 - [BPM] Camunda external task: consider resume on fail parameter from BPM

==== Bug fixes

* MSA-7939 - [Workflow] Variable type isn't correctly persisted in $context
* MSA-8192 - [Microservice] Microservice can be saved with empty name
* MSA-8205 - [Workflow] cannot create process the first time you create a workflow
* MSA-8319 - [UI] issue with display (and data) when logged as manager
* MSA-8621 - [API] Provisioning AWS Generic : not use ListAccessKeys
* MSA-8657 - [API] Activate a ME without connection is missing
* MSA-8661 - [API] SecEngine DeviceId.php is updated only at the time of initial provisioning
* MSA-8682 - [Upgrade] Some files are not changed after pulling the new images
* MSA-8742 - [Managed Entities] Autofill the external reference field with the database UBI ID
* MSA-8743 - [Workflow] $context doesn't correctly pass list() between tasks
* MSA-8744 - [API] license upload issue
* MSA-8754 - [Workflow] Variable name with deep object does not store its value
* MSA-8780 - [Workflow] workflow attachment : not possible to remove attached subtenant
* MSA-8797 - [Alarm] Show all workflows in alarm edition, even when subtenant is selected
* MSA-8800 - [UI/Admin] when deleting a subtenant, workflow must be detached as well
* MSA-8809 - [HA - Activation of ME not possible on HA
* MSA-8877 - [Workflow] Ping Python workflow always returns success, even for non reachable IP
* MSA-8878 - [Deployment Setting] Deployment setting do not work if wildfly debug is activated
* MSA-8887 - [CoreEngine] sms_polld ping retries are not correct
* MSA-8909 - [UI/Search] Regression - filter input is not working
* MSA-8919 - [Alarm] No more possible to edit an alarm rule
* MSA-8933 - [Microservice] Fix routing issue for the microservice console
* MSA-8948 - [UI] You cannot delete a sub-tenant on msa2.ubiqube.com
* MSA-8960 - [API] API returning wrong microservices URIs
* MSA-8961 - [Workflow] Unable to load microservice object
* MSA-8967 - [Workflow] process scheduling button is visible although scheduling is not supported
* MSA-8983 - [Microservice] in some cases, the "Import" section of XML microservice can't be edited
* MSA-8995 - [Workflow] some inconsitancies found in workflow data (graphs + instance counts)
* MSA-8996 - [User Management] not possible to detach/attach subtenant to an edited manager
* MSA-9086 - [Workflow] Array variables not displayed properly in the workflow console is causing all values to be lost in the backend for next process invocation
