name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the doc
      run: docker build -t ubi.docs .
      
    - name: Run the Docker image
      run: |
        docker run --name temp_container ubi.docs
        echo $pwd
        docker cp temp_container:/home/gradle/build/ /tmp
        docker rm temp_container
      
    - name: Configure Git
      run: |
        git config --global user.email "dmn@ubiqube"
        git config --global user.name "dmn"

    - name: Commit and push changes
      run: |
        cd /tmp
        ls -ltr
